# Generated by Django 3.0.8 on 2020-07-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='univpage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
