# Generated by Django 3.0.8 on 2020-07-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0002_univpage_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='univpage',
            old_name='intro',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='univpage',
            name='description',
        ),
    ]
