# Generated by Django 3.0.8 on 2020-07-20 16:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0004_univpage_major1'),
    ]

    operations = [
        migrations.AddField(
            model_name='univpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add addtional text', required=True))]))], blank=True, null=True),
        ),
    ]
