# Generated by Django 3.0.8 on 2020-07-21 04:04

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0005_univpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='univpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='univpage',
            name='major1',
        ),
        migrations.RemoveField(
            model_name='univpage',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='univpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.RichTextBlock())])), ('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True),
        ),
    ]
