# Generated by Django 3.0.8 on 2020-07-28 08:39

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0006_auto_20200721_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True))])), ('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True),
        ),
    ]
