# Generated by Django 3.0 on 2020-11-22 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContensPage',
            fields=[
                ('mintopage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='minto.MintoPAge')),
            ],
            options={
                'abstract': False,
            },
            bases=('minto.mintopage',),
        ),
    ]
