# Generated by Django 3.0 on 2020-11-22 09:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('minto', '0002_contenspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mintopage',
            name='UNIV',
            field=wagtail.core.fields.StreamField([('UNIV', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(blank=True, help_text='大学名', max_length=100, null=True)), ('sub', wagtail.core.blocks.CharBlock(blank=True, help_text='区分/地名', max_length=100, null=True)), ('text', wagtail.core.blocks.TextBlock(require=True)), ('images', wagtail.images.blocks.ImageChooserBlock(label='Image'))]))], blank=True, null=True),
        ),
    ]
