# Generated by Django 3.0 on 2020-11-22 09:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('minto', '0005_auto_20201122_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentspage',
            name='VALUE',
            field=wagtail.core.fields.StreamField([('INDEX', wagtail.core.blocks.StructBlock([('int1', wagtail.core.blocks.IntegerBlock(blank=True, help_text='500~600点', null=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentspage',
            name='mintopage_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='minto.MintoPage'),
        ),
    ]
