# Generated by Django 3.0 on 2020-11-22 10:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('minto', '0006_auto_20201122_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='mintopage',
            name='RESEARCH',
            field=wagtail.core.fields.StreamField([('RESEARCH', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(blank=True, help_text='研究科名', max_length=100, null=True)), ('link', wagtail.core.blocks.CharBlock(blank=True, help_text='研究科名のリンク', max_length=100, null=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentspage',
            name='mintopage_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='minto.MintoPage'),
        ),
    ]
