# Generated by Django 3.0 on 2020-12-04 12:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('minto', '0013_auto_20201126_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentspage',
            name='INDEX',
            field=wagtail.core.fields.StreamField([('INDEX', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(blank=True, default='研究科', help_text='研究科名', max_length=100, null=True)), ('link', wagtail.core.blocks.CharBlock(blank=True, help_text='研究科名のURL', max_length=100, null=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentspage',
            name='VALUE',
            field=wagtail.core.fields.StreamField([('INDEX', wagtail.core.blocks.StructBlock([('research_name', wagtail.core.blocks.CharBlock(blank=True, help_text='研究科名', max_length=100, null=True)), ('IDname', wagtail.core.blocks.CharBlock(blank=True, default='Chart', help_text='IDname', max_length=100, null=True)), ('RinkID', wagtail.core.blocks.CharBlock(blank=True, help_text='RinkID', max_length=100, null=True)), ('int1', wagtail.core.blocks.IntegerBlock(blank=True, help_text='500~600点', null=True)), ('int2', wagtail.core.blocks.IntegerBlock(blank=True, help_text='600~700点', null=True)), ('int3', wagtail.core.blocks.IntegerBlock(blank=True, help_text='700~800点', null=True)), ('int4', wagtail.core.blocks.IntegerBlock(blank=True, help_text='800~900点', null=True)), ('int5', wagtail.core.blocks.IntegerBlock(blank=True, help_text='900点以上', null=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentspage',
            name='mintopage_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='minto.MintoPage'),
        ),
        migrations.AlterField(
            model_name='mintopage',
            name='UNIV',
            field=wagtail.core.fields.StreamField([('UNIV', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(blank=True, help_text='大学名', max_length=100, null=True)), ('sub', wagtail.core.blocks.CharBlock(blank=True, help_text='区分/地名', max_length=100, null=True)), ('link', wagtail.core.blocks.CharBlock(blank=True, help_text='大学名のリンク -uは不要', max_length=100, null=True)), ('text', wagtail.core.blocks.TextBlock(require=True)), ('images', wagtail.images.blocks.ImageChooserBlock(label='Image'))]))], blank=True, null=True),
        ),
    ]
