# Generated by Django 3.0 on 2021-01-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201126_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
