# Generated by Django 3.0.8 on 2020-07-30 03:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_auto_20200730_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(blank=True, help_text='Add about title', max_length=100, null=True)), ('text', wagtail.core.blocks.RichTextBlock(blank=True, help_text='Add about content', max_length=1000, null=True))]))], blank=True, null=True),
        ),
    ]
