# Generated by Django 3.0.8 on 2020-08-02 08:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0004_auto_20200730_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulepage',
            name='content',
        ),
        migrations.AddField(
            model_name='rulepage',
            name='rule_content',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(blank=True, help_text='Add about title', max_length=100, null=True)), ('text', wagtail.core.blocks.RichTextBlock(blank=True, help_text='Add about content', max_length=1000, null=True))])), ('date', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.RichTextBlock(blank=True, help_text='Add your Date', max_length=1000, null=True))]))], blank=True, null=True),
        ),
    ]
