# Generated by Django 3.0.8 on 2020-07-28 08:43

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200719_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
