# Generated by Django 3.0.8 on 2020-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='news',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
