# Generated by Django 3.0.8 on 2020-07-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200728_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='news',
        ),
    ]
