# Generated by Django 3.0.8 on 2020-07-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='news',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
