# Generated by Django 3.0.8 on 2020-07-28 09:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200728_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='news',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
