# Generated by Django 3.0.8 on 2020-07-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200728_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='news',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
