# Generated by Django 3.0.8 on 2020-08-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200802_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='content_home',
        ),
    ]
