# Generated by Django 3.0.8 on 2020-08-02 13:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_homepage_content_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, help_text='Add news title', max_length=100, null=True)), ('link', wagtail.core.blocks.CharBlock(blank=True, help_text='Add news link', max_length=100, null=True))]))], blank=True, null=True),
        ),
    ]
