# Generated by Django 3.0.8 on 2020-08-20 12:54

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('first', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True))])), ('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True)),
                ('second', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True))])), ('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True)),
                ('third', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True))])), ('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True)),
                ('four', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True))])), ('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True)),
                ('five', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True))])), ('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Answer Page',
                'verbose_name_plural': 'Answer Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='AnserPage',
        ),
    ]
