# Generated by Django 3.0.8 on 2020-08-22 03:43

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_auto_20200820_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpage',
            name='first',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True))])), ('full_richtext', streams.blocks.RichtextBlockAns())], blank=True, null=True),
        ),
    ]
