# Generated by Django 3.0 on 2021-01-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0007_answerpage__2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerpage',
            old_name='_2020',
            new_name='year_2020',
        ),
    ]
