# Generated by Django 3.0 on 2021-01-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0008_auto_20210103_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerpage',
            old_name='first',
            new_name='year_2019',
        ),
    ]
