# Generated by Django 3.0 on 2021-01-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0009_auto_20210103_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerpage',
            old_name='eight',
            new_name='year_2011',
        ),
        migrations.RenameField(
            model_name='answerpage',
            old_name='five',
            new_name='year_2012',
        ),
        migrations.RenameField(
            model_name='answerpage',
            old_name='four',
            new_name='year_2013',
        ),
        migrations.RenameField(
            model_name='answerpage',
            old_name='nine',
            new_name='year_2014',
        ),
        migrations.RenameField(
            model_name='answerpage',
            old_name='second',
            new_name='year_2015',
        ),
        migrations.RenameField(
            model_name='answerpage',
            old_name='seven',
            new_name='year_2016',
        ),
        migrations.RenameField(
            model_name='answerpage',
            old_name='six',
            new_name='year_2017',
        ),
        migrations.RenameField(
            model_name='answerpage',
            old_name='third',
            new_name='year_2018',
        ),
    ]
