# Generated by Django 3.0.8 on 2020-07-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='intro',
        ),
    ]
