# Generated by Django 3.0.8 on 2020-08-20 12:01

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans_univPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True))])), ('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ans_univ Page',
                'verbose_name_plural': 'Ans_univ Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
