# Generated by Django 3.0.8 on 2020-07-27 10:19

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200727_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadpage',
            options={},
        ),
        migrations.AlterField(
            model_name='formfield',
            name='Page',
            field=modelcluster.fields.ParentalKey(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('document', 'ファイルアップロード')], on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='upload.UploadPage'),
        ),
    ]
