# Generated by Django 3.0.8 on 2020-07-29 14:15

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutpage_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
