# Generated by Django 3.0.8 on 2020-07-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_aboutpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='about_text',
        ),
    ]
