# Generated by Django 3.0 on 2020-10-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name', max_length=100, null=True)),
                ('message', models.TextField(max_length=300)),
                ('date', models.DateField(verbose_name='打刻日')),
                ('rate', models.IntegerField(choices=[(1, '合ってる(8割)'), (2, '概ね合ってる（6割）'), (3, 'あまり合っていない（４割）'), (4, '合ってない(４割以下)')], default=None, verbose_name='正答率')),
            ],
        ),
    ]
