# Generated by Django 3.0.8 on 2020-08-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailspage',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
