# Generated by Django 3.0.8 on 2020-08-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_detailspage_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailspage',
            name='university_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
