# Generated by Django 3.0 on 2020-10-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_commentimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentimage',
            options={'verbose_name': 'Detail Image Page'},
        ),
    ]
