# Generated by Django 3.0 on 2020-10-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('details', '0003_auto_20201003_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='univ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CommentImage',
        ),
    ]
