# Generated by Django 3.0 on 2020-10-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20201011_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
