# Generated by Django 3.0.8 on 2020-08-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('details', '0004_auto_20200823_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='Page',
        ),
        migrations.DeleteModel(
            name='DetailsPage',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
