# Generated by Django 3.0 on 2020-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_comment_subject_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ImageField(upload_to='upload/')),
                ('univ', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_year', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
