# Generated by Django 3.0 on 2020-10-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='subject_year',
        ),
        migrations.RemoveField(
            model_name='image',
            name='univ',
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='details.Comment', verbose_name='投稿'),
        ),
    ]
