# Generated by Django 3.0.8 on 2020-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
