# Generated by Django 3.0 on 2020-10-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_auto_20201012_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='subject_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='univ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
