# Generated by Django 3.0 on 2020-10-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_auto_20201012_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='打刻日'),
        ),
    ]
