# Generated by Django 3.0.8 on 2020-07-27 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_auto_20200727_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Upload Page', 'verbose_name_plural': 'Upload Pages'},
        ),
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
