# Generated by Django 3.0.8 on 2020-07-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_auto_20200727_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='subtitle',
            field=models.CharField(max_length=100, null=True, verbose_name='研究科名'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=200, verbose_name='大学名'),
        ),
    ]
