# Generated by Django 3.0.8 on 2020-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0005_auto_20200727_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='subfield',
            field=models.CharField(max_length=100, null=True, verbose_name='専攻以下'),
        ),
    ]
