# Generated by Django 3.0.8 on 2020-08-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0006_file_subfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='subfield',
            field=models.CharField(help_text='<p>できるだけ正確に記入してください</p>', max_length=100, null=True, verbose_name='専攻以下'),
        ),
        migrations.AlterField(
            model_name='file',
            name='subtitle',
            field=models.CharField(help_text='<p></p>', max_length=100, null=True, verbose_name='研究科名'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(help_text='<p></p>', max_length=200, verbose_name='大学名'),
        ),
        migrations.AlterField(
            model_name='file',
            name='year',
            field=models.IntegerField(default=2019, help_text='<p>受験した年を入力してください<br>(例)2020年入学者用問題→2019年</p>', verbose_name='年度'),
        ),
    ]
