# Generated by Django 3.0.8 on 2020-07-30 03:12

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
