# Generated by Django 3.0.8 on 2020-08-20 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(help_text='<p></p>', max_length=200, verbose_name='大学名')),
                ('subtitle', models.CharField(help_text='<p></p>', max_length=100, null=True, verbose_name='研究科名')),
                ('subfield', models.CharField(help_text='<p>できるだけ正確に記入してください</p>', max_length=100, null=True, verbose_name='専攻以下')),
                ('subject', models.CharField(help_text='<p></p>', max_length=100, null=True, verbose_name='教科等')),
                ('year', models.IntegerField(default=2019, help_text='<p>受験した年を入力してください<br>(例)2020年入学者用問題→2019年</p>', verbose_name='年度')),
                ('file', models.FileField(upload_to='past/', verbose_name='過去問')),
            ],
            options={
                'verbose_name': 'Ans_Upload Page',
                'verbose_name_plural': 'Ans_Upload Pages',
            },
        ),
    ]
