# Generated by Django 3.0 on 2020-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans_upload', '0002_auto_20201001_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='<p>png,jpeg,svg,bmp</p>', upload_to='past/', verbose_name='過去問解答'),
        ),
    ]
