# Generated by Django 3.0 on 2020-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans_upload', '0004_auto_20201126_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, help_text='<p>png,jpeg,svg,bmp</p>', upload_to='past/', verbose_name='過去問解答'),
        ),
    ]
