# Generated by Django 3.0 on 2020-12-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans_upload', '0006_auto_20201204_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file2',
            field=models.FileField(blank=True, upload_to='past/'),
        ),
        migrations.AddField(
            model_name='file',
            name='file3',
            field=models.FileField(blank=True, upload_to='past/'),
        ),
    ]
