# Generated by Django 3.0 on 2020-12-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ans_upload', '0009_auto_20201204_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file4',
            field=models.FileField(blank=True, upload_to='past/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='file',
            name='file5',
            field=models.FileField(blank=True, upload_to='past/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='file2',
            field=models.FileField(blank=True, upload_to='past/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='file3',
            field=models.FileField(blank=True, upload_to='past/', verbose_name=''),
        ),
    ]
